### ISSUE TITLE
Error: listen EADDRINUSE: address already in use :::9998

### ISSUE THREAD

**Issue by phillipmohr** [dockware/dockware#162]
Hey, when I call the function `make watch-storefront` in the docker container I sometimes get the error message `Error: listen EADDRINUSE: address already in use :::9998`. When I restart the computer it usually works again, but I don't want to restart it everytime.

I'm a docker newbie so maybe this is a stupid question... But there is no other container that is running. 

How can I fix this error?

- Image: dockware/dev:6.4.18.1
- MacOS Ventura 13.0.1
- ports:
         - "80:80"
         - "3306:3306"
         - "22:22"
         - "8888:8888"
         - "9999:9999"
         - "9998:9998"

Full error:

```
############
Storefront proxy server started at http://localhost:9998
############


events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::9998
    at Server.setupListenHandle [as _listen2] (net.js:1316:16)
    at listenInCluster (net.js:1364:12)
    at Server.listen (net.js:1450:7)
    at createProxyServer (/var/www/html/vendor/shopware/storefront/Resources/app/storefront/build/proxy-server-hot/index.js:71:8)
    at /var/www/html/vendor/shopware/storefront/Resources/app/storefront/build/start-hot-reload.js:24:5
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1343:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 9998
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sw-next-storefront@1.0.0 hot-proxy: `NODE_ENV=development MODE=hot node ./build/start-hot-reload.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sw-next-storefront@1.0.0 hot-proxy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/www/.npm/_logs/2023-03-20T08_25_44_355Z-debug.log
makefile:60: recipe for target 'watch-storefront' failed
make: *** [watch-storefront] Error 1
```

If more information is needed let me know! Thank you

**Comment by miko007** [comment]
i have the exact same error, running on macOS. everthing was working as expected, for several weeks. then, just randomly during development, this error occured, without anything changed on the container config, and it is not going away since.
